Fix load errors in release workflow.
The release workflow was broken by #794. It's currently failing with:

```
LoadError: cannot load such file -- elastic_graph/support/json_schema/validator_factory (LoadError)
/home/runner/work/elasticgraph/elasticgraph/config/site/support/config_doc_generator.rb:9:in '<top (required)>'
/home/runner/work/elasticgraph/elasticgraph/config/site/Rakefile:649:in 'Kernel#require_relative'
/home/runner/work/elasticgraph/elasticgraph/config/site/Rakefile:649:in 'ElasticGraph::SiteRakeTasks#generate_and_stage_config_documentation'
/home/runner/work/elasticgraph/elasticgraph/config/site/Rakefile:636:in 'ElasticGraph::SiteRakeTasks#stage_markdown_files'
/home/runner/work/elasticgraph/elasticgraph/config/site/Rakefile:593:in 'ElasticGraph::SiteRakeTasks#yard_cmd'
```

This fixes it.